version: 2
defaults: &defaults
  working_directory: ~/opencv
  machine: true

jobs:
  build_arm:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build image for arm
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset && docker build . 

workflows:
  version: 2
  compile-build-and-deploy:
    jobs:
      - build_arm
